In [5]:
import numpy as np  #alias

In [7]:
arr = np.arange(0,40,4)

In [8]:
arr

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

# Bracket Indexing and Selection

In [9]:
arr[2]

8

In [10]:
#getting values in a range
arr[1:5]

array([ 4,  8, 12, 16])

# Broadcasting

numpy arrays are different from normal python list because of their ability to broadcast

In [11]:
arr[1] = 100

In [12]:
arr

array([  0, 100,   8,  12,  16,  20,  24,  28,  32,  36])

In [16]:
arr[1:5] = 100

In [17]:
arr

array([  0, 100, 100, 100, 100,  20,  24,  28,  32,  36])

In [38]:
arr = np.arange(0,40,4)
arr

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [39]:
arr_dup = arr.copy()

In [40]:
slice_of_arr = arr_dup[0:6]
slice_of_arr

array([ 0,  4,  8, 12, 16, 20])

In [41]:
slice_of_arr[:] = 10
slice_of_arr

array([10, 10, 10, 10, 10, 10])

In [42]:
arr_dup

array([10, 10, 10, 10, 10, 10, 24, 28, 32, 36])

In [43]:
arr

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

# Indexing of 2-D array

arr_2d[row][col] 

arr_2d[row,col]

In [44]:
arr_2d = np.array(([1,2,3],[11,22,33],[111,222,333]))
arr_2d

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [54]:
arr_2d[1]

array([11, 22, 33])

In [46]:
arr_2d[-2]

array([11, 22, 33])

In [47]:
arr_2d[1,2]

33

In [48]:
arr_2d[-2,-1]

33

In [52]:
arr_2d[:,2]

array([  3,  33, 333])

In [56]:
arr_2d

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [55]:
arr_2d[1:, 1:]

array([[ 22,  33],
       [222, 333]])

# Selection

In [57]:
arr_sec = np.arange(1,21)

In [58]:
arr_sec

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
bool_arr = arr_sec> 2**3
bool_arr

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [61]:
arr_sec[bool_arr]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [63]:
arr_sec[arr_sec>2**3]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [64]:
arr_sec[arr_sec<11]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr1 = np.random.randint(1,50,50).reshape(10,5)
arr1

array([[24,  3, 25, 16, 49],
       [22,  6, 30, 46, 44],
       [12, 36, 48,  8, 42],
       [ 1, 29, 20,  4, 46],
       [45, 43, 38, 11, 11],
       [47, 35, 19, 16, 28],
       [30, 45, 19,  2, 19],
       [ 9, 35, 20,  1, 29],
       [45, 49, 28, 38, 29],
       [33, 36, 25, 31,  4]])

# Arithmetic

In [70]:
arr

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [71]:
arr*3

array([  0,  12,  24,  36,  48,  60,  72,  84,  96, 108])

In [72]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [73]:
arr/arr

C:\Users\shrey\AppData\Local\Temp\ipykernel_5376\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [74]:
1/arr

C:\Users\shrey\AppData\Local\Temp\ipykernel_5376\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 0.25      , 0.125     , 0.08333333, 0.0625    ,
       0.05      , 0.04166667, 0.03571429, 0.03125   , 0.02777778])

In [75]:
arr**0.5

array([0.        , 2.        , 2.82842712, 3.46410162, 4.        ,
       4.47213595, 4.89897949, 5.29150262, 5.65685425, 6.        ])

# Universal Array Functions

In [76]:
np.sqrt(arr)

array([0.        , 2.        , 2.82842712, 3.46410162, 4.        ,
       4.47213595, 4.89897949, 5.29150262, 5.65685425, 6.        ])

In [78]:
np.exp(arr) #e^

array([1.00000000e+00, 5.45981500e+01, 2.98095799e+03, 1.62754791e+05,
       8.88611052e+06, 4.85165195e+08, 2.64891221e+10, 1.44625706e+12,
       7.89629602e+13, 4.31123155e+15])

In [79]:
np.max(arr) #same as arr.max()

36

In [80]:
np.sin(arr)

array([ 0.        , -0.7568025 ,  0.98935825, -0.53657292, -0.28790332,
        0.91294525, -0.90557836,  0.27090579,  0.55142668, -0.99177885])

In [81]:
np.log10(arr)

C:\Users\shrey\AppData\Local\Temp\ipykernel_5376\2153533263.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)


array([      -inf, 0.60205999, 0.90308999, 1.07918125, 1.20411998,
       1.30103   , 1.38021124, 1.44715803, 1.50514998, 1.5563025 ])